#!/bin/bash

sudo docker rmi ncsu-app
sudo docker rmi localhost:5000/ncsu:latest
sudo docker build -t ncsu-app .
sudo docker tag -f ncsu-app localhost:5000/ncsu:latest
sudo docker push localhost:5000/ncsu:latest
